Fix RangeReplaceableCollection conformance for latest Swift version
fireblade-engine/math pull request #9
Opened 2022-11-01 02:41 UTC by stackotter

### Description

This library fails to build on both Linux and macOS when using Swift 5.7 and this PR fixes that. Here's the error I ran into:

```
/root/DeltaClient/.build/checkouts/math/Sources/FirebladeMath/Matrix/MatrixStorage+NO_SIMD.swift:10:15: error: type 'Storage3x3<Value>' does not conform to protocol 'RangeReplaceableCollection'
public struct Storage3x3<Value>: Storage3x3Protocol where Value: StorageScalar {
              ^
/root/DeltaClient/.build/checkouts/math/Sources/FirebladeMath/Matrix/MatrixStorage+NO_SIMD.swift:10:15: error: unavailable instance method 'replaceSubrange(_:with:)' was used to satisfy a requirement of protocol 'RangeReplaceableCollection'
public struct Storage3x3<Value>: Storage3x3Protocol where Value: StorageScalar {
              ^
Swift.RangeReplaceableCollection:4:26: note: 'replaceSubrange(_:with:)' declared here
    public mutating func replaceSubrange<C>(_ subrange: Range<Self.Index>, with newElements: C) where C : Collection, Self.Element == C.Element
                         ^
Swift.RangeReplaceableCollection:4:19: note: requirement 'replaceSubrange(_:with:)' declared here
    mutating func replaceSubrange<C>(_ subrange: Range<Self.Index>, with newElements: __owned C) where C : Collection, Self.Element == C.Element
                  ^
```

To fix this I implemented `replaceSubrange` for `Matrix3x3Protocol` and `Matrix4x4Protocol` as sensibly as possible. I introduced the requirement that `subrange` and `newElements` are the same length because when working with a Matrix (essentially a fixed-length array), there's no sensible way to interpret the case where they aren't the same length without just silently failing.

### Detailed Design

It seems as though the old code relied on a stdlib `replaceSubrange` default implementation that has since been removed or become non-applicable to the type. My changes shouldn't be making any changes to the public API of the library although I'm not exactly sure what the old `replaceSubrange` implementation used to do in the case where the `subrange` and `newElements` aren't the same length.

### Documentation

I've added a documentation comment explaining the precondition that `subrange` and `newElements` must be the same length.

### Testing

The tests still pass.

### Performance

The change doesn't seem very performance related to me. I don't think the default implementation would've performed any differently.

### Source Impact

It should have no source impact other than that packages that rely on this will now work with the latest Swift version :)

### Checklist

- [x] I've read the [Contribution Guidelines](https://github.com/fireblade-engine/math/blob/master/CONTRIBUTING.md)
- [x] I've followed the coding style of the rest of the project.
- [x] I've added tests covering all new code paths my change adds to the project (to the extent possible).
- [x] I've added benchmarks covering new functionality (if appropriate).
- [x] I've verified that my change does not break any existing tests or introduce unexpected benchmark regressions.
- [x] I've updated the documentation (if appropriate).

2022-11-01 02:47 UTC, stackotter commented
The Linux test action seems to be failing but not because of the code changes. It seems like the action runner is just missing the `make` command.

2022-11-01 02:53 UTC, stackotter commented
And the Windows action failed too but that seems to be because of a manifest parsing error or a linking error. Neither of which should've been caused by my changes.

I can confirm that this PR builds on Linux (in the swift 5.7 Ubuntu Jammy nightly Docker container) but I have not tested it on Windows (but I believe that the changes are simple enough that they should just work).

2022-11-02 07:26 UTC, ctreffs requested changes

2022-11-02 07:26 UTC, ctreffs commented on Sources/FirebladeMath/Matrix/MatrixStorage.swift
> +        precondition(subrange.count != newElements.count, "newElements must be the same length as subrange")
I think this is must be `subrange.count == newElements.count` - otherwise this will always fail for same element counts

2022-11-02 07:26 UTC, ctreffs commented on Sources/FirebladeMath/Matrix/MatrixStorage.swift
> +        precondition(subrange.count != newElements.count, "newElements must be the same length as subrange")
Same here `subrange.count == newElements.count`

2022-11-02 07:27 UTC, ctreffs commented
Thanks for your contribution 👍 - will have a look at the CI scripts, when I find the time

2022-11-02 08:16 UTC, ctreffs commented
I've updated your branch with the CI changes from master and all the tests seem to run properly with the exception of Windows - I have no idea what is happening there 😄

2022-11-02 08:37 UTC, stackotter commented
Whoops 🤦‍♂️ I don't know how I got those preconditions backwards lol, nice catch. Fixed them now

2022-11-02 09:10 UTC, ctreffs commented
LGTM 🚀

2022-11-02 09:10 UTC, merged